/**
 * Generate TypeScript data files from the SQLite database.
 * Output files must be compatible with existing website page imports.
 */

import { getDb, migrate } from "../lib/db";
import { saveDataFile } from "../lib/storage";

export interface GenerateResult {
  modelsGenerated: number;
  filesWritten: string[];
}

interface ModelRow {
  slug: string;
  name: string;
  alternate_name: string | null;
  developer: string;
  developer_url: string | null;
  developer_logo_url: string | null;
  params: string | null;
  context_window: string | null;
  license: string | null;
  license_status: string;
  category: string | null;
  release_date: string | null;
  description_zh: string | null;
  description_ja: string | null;
  strengths: string | null;
  weaknesses: string | null;
  use_cases: string | null;
  links_json: string | null;
  hf_model_id: string | null;
  datalearner_slug: string | null;
  pricing_json: string | null;
  is_core: number;
  is_japanese: number;
  priority: number;
}

function parseJSON<T>(json: string | null, fallback: T): T {
  if (!json) return fallback;
  try {
    return JSON.parse(json) as T;
  } catch {
    return fallback;
  }
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

export function generateDataFiles(): GenerateResult {
  migrate();
  const db = getDb();

  console.log("\n═══ Stage 4: Generate ═══");

  const models = db.prepare(
    "SELECT * FROM models ORDER BY priority DESC, is_japanese ASC, release_date DESC NULLS LAST, name"
  ).all() as ModelRow[];

  // Generate src/data/models.ts
  const modelEntries = models.map((m) => {
    const links = parseJSON<Record<string, string>>(m.links_json, {});
    const pricing = parseJSON<{
      inputPer1M: number | null;
      outputPer1M: number | null;
      currency: string;
      billingMode: string;
      url: string | null;
    } | null>(m.pricing_json, null);
    const strengths = parseJSON<string[]>(m.strengths, []);
    const weaknesses = parseJSON<string[]>(m.weaknesses, []);
    const useCases = parseJSON<string[]>(m.use_cases, []);

    // Map category to the type field expected by the website
    const typeMap: Record<string, string> = {
      reasoning: "reasoning",
      foundation: "foundation",
      chat: "chat",
      coder: "coder",
      embedding: "foundation",
      multimodal: "foundation",
      voice: "foundation",
    };
    const type = typeMap[m.category || "foundation"] || "foundation";

    return `  {
    slug: "${escapeStr(m.slug)}",
    name: "${escapeStr(m.name)}",
    developer: "${escapeStr(m.developer)}",
    developerUrl: "${escapeStr(m.developer_url || "")}",
    params: "${escapeStr(m.params || "非公開")}",
    contextWindow: "${escapeStr(m.context_window || "")}",
    license: "${escapeStr(m.license || "プロプライエタリ")}",
    openSource: "${m.license_status}" as const,
    type: "${type}" as const,
    releaseDate: "${escapeStr(m.release_date || "")}",
    pricing: ${pricing ? `{
      inputPer1M: ${pricing.inputPer1M ?? "null"},
      outputPer1M: ${pricing.outputPer1M ?? "null"},
      currency: "${pricing.currency}" as const,
      billingMode: "${escapeStr(pricing.billingMode)}",
      url: ${pricing.url ? `"${escapeStr(pricing.url)}"` : "null"},
    }` : "null"},
    descriptionJa: "${escapeStr(m.description_ja || "")}",
    strengths: ${JSON.stringify(strengths)},
    weaknesses: ${JSON.stringify(weaknesses)},
    useCases: ${JSON.stringify(useCases)},
    links: {
      ${links.official ? `official: "${escapeStr(links.official)}",` : ""}
      ${links.huggingface ? `huggingface: "${escapeStr(links.huggingface)}",` : ""}
      ${links.paper ? `paper: "${escapeStr(links.paper)}",` : ""}
      ${links.api ? `api: "${escapeStr(links.api)}",` : ""}
    },
  }`;
  });

  const modelsTs = `// Auto-generated by pipeline/generate-data-files.ts
// Last updated: ${new Date().toISOString()}
// Source: SQLite database (data/crawler.db)
// DO NOT EDIT MANUALLY

export interface ModelDetail {
  slug: string;
  name: string;
  developer: string;
  developerUrl: string;
  params: string;
  contextWindow: string;
  license: string;
  openSource: "open" | "closed" | "open-nc";
  type: "reasoning" | "foundation" | "chat" | "coder";
  releaseDate: string;
  pricing: {
    inputPer1M: number | null;
    outputPer1M: number | null;
    currency: "USD" | "JPY";
    billingMode: string;
    url: string | null;
  } | null;
  descriptionJa: string;
  strengths: string[];
  weaknesses: string[];
  useCases: string[];
  links: {
    official?: string;
    huggingface?: string;
    paper?: string;
    api?: string;
  };
}

export const modelDetails: ModelDetail[] = [
${modelEntries.join(",\n")}
];

export function getModelBySlug(slug: string): ModelDetail | undefined {
  return modelDetails.find((m) => m.slug === slug);
}
`;

  saveDataFile("models.ts", modelsTs);

  // Generate src/data/model-slugs.ts for generateStaticParams
  const slugs = models.map((m) => m.slug);
  const slugsTs = `// Auto-generated by pipeline/generate-data-files.ts
// Last updated: ${new Date().toISOString()}

export const allModelSlugs: string[] = ${JSON.stringify(slugs, null, 2)};
`;
  saveDataFile("model-slugs.ts", slugsTs);

  // Generate leaderboard.ts from leaderboard_scores table
  generateLeaderboardFile(db);

  // Generate pricing.ts from pricing_entries table
  generatePricingFile(db);

  console.log(`  Generated ${models.length} models in models.ts and model-slugs.ts`);

  return {
    modelsGenerated: models.length,
    filesWritten: ["src/data/models.ts", "src/data/model-slugs.ts", "src/data/leaderboard.ts", "src/data/pricing.ts"],
  };
}

// ── Leaderboard generation ──

interface LeaderboardRow {
  id: number;
  name: string;
  developer: string;
  license_status: string;
  category: string | null;
  release_date: string | null;
}

interface ScoreRow {
  model_id: number;
  benchmark: string;
  score: number;
}

function generateLeaderboardFile(db: ReturnType<typeof getDb>): void {
  console.log("  Generating leaderboard.ts...");

  // Get all models that have at least one leaderboard score
  const modelsWithScores = db.prepare(`
    SELECT DISTINCT m.id, m.name, m.developer, m.license_status, m.category, m.release_date
    FROM models m
    INNER JOIN leaderboard_scores ls ON ls.model_id = m.id
    ORDER BY m.name
  `).all() as LeaderboardRow[];

  if (modelsWithScores.length === 0) {
    console.log("  No leaderboard scores in DB, skipping leaderboard.ts generation");
    return;
  }

  // Get all scores
  const allScores = db.prepare("SELECT model_id, benchmark, score FROM leaderboard_scores").all() as ScoreRow[];

  // Build score map: model_id -> { benchmark: score }
  const scoreMap = new Map<number, Record<string, number>>();
  for (const s of allScores) {
    if (!scoreMap.has(s.model_id)) scoreMap.set(s.model_id, {});
    scoreMap.get(s.model_id)![s.benchmark] = s.score;
  }

  // Build ranking entries
  const typeMap: Record<string, string> = {
    reasoning: "reasoning",
    foundation: "foundation",
    chat: "chat",
    coder: "coder",
    embedding: "foundation",
    multimodal: "foundation",
    voice: "foundation",
  };

  const entries = modelsWithScores.map((m) => {
    const scores = scoreMap.get(m.id) || {};
    return {
      name: m.name,
      developer: m.developer,
      hle: scores.hle ?? null,
      arcAgi2: scores.arcAgi2 ?? null,
      frontierMath: scores.frontierMath ?? null,
      sweBenchVerified: scores.sweBenchVerified ?? null,
      tauBench: scores.tauBench ?? null,
      openSource: m.license_status as "open" | "closed" | "open-nc",
      type: (typeMap[m.category || "foundation"] || "foundation") as "reasoning" | "foundation" | "chat" | "coder",
      releaseDate: m.release_date || "",
    };
  });

  // Sort by HLE descending, then by name
  entries.sort((a, b) => {
    const aHle = a.hle ?? 0;
    const bHle = b.hle ?? 0;
    if (bHle !== aHle) return bHle - aHle;
    return a.name.localeCompare(b.name);
  });

  // Add rank
  const ranked = entries.map((e, i) => ({ rank: i + 1, ...e }));

  const data = JSON.stringify(ranked, null, 2);

  const leaderboardTs = `// Auto-generated by pipeline/generate-data-files.ts
// Last updated: ${new Date().toISOString()}
// Source: SQLite database (leaderboard_scores table)
// DO NOT EDIT MANUALLY

export interface ModelRanking {
  rank: number;
  name: string;
  developer: string;
  hle: number | null;
  arcAgi2: number | null;
  frontierMath: number | null;
  sweBenchVerified: number | null;
  tauBench: number | null;
  openSource: "open" | "closed" | "open-nc";
  type: "reasoning" | "foundation" | "chat" | "coder";
  releaseDate: string;
}

export const leaderboardData: ModelRanking[] = ${data};
`;

  saveDataFile("leaderboard.ts", leaderboardTs);
  console.log(`  Generated ${ranked.length} leaderboard entries`);
}

// ── Pricing generation ──

interface PricingRow {
  model_name: string;
  provider: string;
  billing_mode: string;
  input_price: number;
  output_price: number;
  input_modality: string;
  output_modality: string;
  currency: string | null;
  notes: string | null;
  release_date: string | null;
}

function generatePricingFile(db: ReturnType<typeof getDb>): void {
  console.log("  Generating pricing.ts...");

  const entries = db.prepare(`
    SELECT p.model_name, p.provider, p.billing_mode, p.input_price, p.output_price,
           p.input_modality, p.output_modality, p.currency, p.notes,
           m.release_date
    FROM pricing_entries p
    LEFT JOIN models m ON p.model_id = m.id
    ORDER BY p.provider, p.model_name, p.billing_mode
  `).all() as PricingRow[];

  if (entries.length === 0) {
    console.log("  No pricing entries in DB, skipping pricing.ts generation");
    return;
  }

  const outputEntries = entries.map((e) => ({
    modelName: e.model_name,
    provider: e.provider,
    billingMode: e.billing_mode,
    inputPrice: e.input_price,
    outputPrice: e.output_price,
    inputModality: e.input_modality,
    outputModality: e.output_modality,
    releaseDate: e.release_date || new Date().toISOString().slice(0, 10),
    ...(e.notes ? { notes: e.notes } : {}),
  }));

  const data = JSON.stringify(outputEntries, null, 2);

  const pricingTs = `// Auto-generated by pipeline/generate-data-files.ts
// Last updated: ${new Date().toISOString()}
// Source: SQLite database (pricing_entries table)
// DO NOT EDIT MANUALLY

export type BillingMode = "standard" | "batch" | "cache" | "long-context";

export interface PricingEntry {
  modelName: string;
  provider: string;
  billingMode: BillingMode;
  inputPrice: number;
  outputPrice: number;
  inputModality: "text" | "multimodal";
  outputModality: "text" | "multimodal";
  releaseDate: string;
  notes?: string;
}

export const pricingData: PricingEntry[] = ${data};
`;

  saveDataFile("pricing.ts", pricingTs);
  console.log(`  Generated ${entries.length} pricing entries`);
}