/**
 * Generate TypeScript data files from the SQLite database.
 * Output files must be compatible with existing website page imports.
 */

import { getDb, migrate } from "../lib/db";
import { saveDataFile } from "../lib/storage";

export interface GenerateResult {
  modelsGenerated: number;
  filesWritten: string[];
}

interface ModelRow {
  slug: string;
  name: string;
  alternate_name: string | null;
  developer: string;
  developer_url: string | null;
  developer_logo_url: string | null;
  params: string | null;
  context_window: string | null;
  license: string | null;
  license_status: string;
  category: string | null;
  release_date: string | null;
  description_zh: string | null;
  description_ja: string | null;
  strengths: string | null;
  weaknesses: string | null;
  use_cases: string | null;
  links_json: string | null;
  hf_model_id: string | null;
  datalearner_slug: string | null;
  pricing_json: string | null;
  is_core: number;
  is_japanese: number;
  priority: number;
}

function parseJSON<T>(json: string | null, fallback: T): T {
  if (!json) return fallback;
  try {
    return JSON.parse(json) as T;
  } catch {
    return fallback;
  }
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

export function generateDataFiles(): GenerateResult {
  migrate();
  const db = getDb();

  console.log("\n═══ Stage 4: Generate ═══");

  const models = db.prepare(
    "SELECT * FROM models ORDER BY priority DESC, is_japanese ASC, release_date DESC NULLS LAST, name"
  ).all() as ModelRow[];

  // Generate src/data/models.ts
  const modelEntries = models.map((m) => {
    const links = parseJSON<Record<string, string>>(m.links_json, {});
    const pricing = parseJSON<{
      inputPer1M: number | null;
      outputPer1M: number | null;
      currency: string;
      billingMode: string;
      url: string | null;
    } | null>(m.pricing_json, null);
    const strengths = parseJSON<string[]>(m.strengths, []);
    const weaknesses = parseJSON<string[]>(m.weaknesses, []);
    const useCases = parseJSON<string[]>(m.use_cases, []);

    // Map category to the type field expected by the website
    const typeMap: Record<string, string> = {
      reasoning: "reasoning",
      foundation: "foundation",
      chat: "chat",
      coder: "coder",
      embedding: "foundation",
      multimodal: "foundation",
      voice: "foundation",
    };
    const type = typeMap[m.category || "foundation"] || "foundation";

    return `  {
    slug: "${escapeStr(m.slug)}",
    name: "${escapeStr(m.name)}",
    developer: "${escapeStr(m.developer)}",
    developerUrl: "${escapeStr(m.developer_url || "")}",
    params: "${escapeStr(m.params || "非公開")}",
    contextWindow: "${escapeStr(m.context_window || "")}",
    license: "${escapeStr(m.license || "プロプライエタリ")}",
    openSource: "${m.license_status}" as const,
    type: "${type}" as const,
    releaseDate: "${escapeStr(m.release_date || "")}",
    pricing: ${pricing ? `{
      inputPer1M: ${pricing.inputPer1M ?? "null"},
      outputPer1M: ${pricing.outputPer1M ?? "null"},
      currency: "${pricing.currency}" as const,
      billingMode: "${escapeStr(pricing.billingMode)}",
      url: ${pricing.url ? `"${escapeStr(pricing.url)}"` : "null"},
    }` : "null"},
    descriptionJa: "${escapeStr(m.description_ja || "")}",
    strengths: ${JSON.stringify(strengths)},
    weaknesses: ${JSON.stringify(weaknesses)},
    useCases: ${JSON.stringify(useCases)},
    links: {
      ${links.official ? `official: "${escapeStr(links.official)}",` : ""}
      ${links.huggingface ? `huggingface: "${escapeStr(links.huggingface)}",` : ""}
      ${links.paper ? `paper: "${escapeStr(links.paper)}",` : ""}
      ${links.api ? `api: "${escapeStr(links.api)}",` : ""}
    },
  }`;
  });

  const modelsTs = `// Auto-generated by pipeline/generate-data-files.ts
// Last updated: ${new Date().toISOString()}
// Source: SQLite database (data/crawler.db)
// DO NOT EDIT MANUALLY

export interface ModelDetail {
  slug: string;
  name: string;
  developer: string;
  developerUrl: string;
  params: string;
  contextWindow: string;
  license: string;
  openSource: "open" | "closed" | "open-nc";
  type: "reasoning" | "foundation" | "chat" | "coder";
  releaseDate: string;
  pricing: {
    inputPer1M: number | null;
    outputPer1M: number | null;
    currency: "USD" | "JPY";
    billingMode: string;
    url: string | null;
  } | null;
  descriptionJa: string;
  strengths: string[];
  weaknesses: string[];
  useCases: string[];
  links: {
    official?: string;
    huggingface?: string;
    paper?: string;
    api?: string;
  };
}

export const modelDetails: ModelDetail[] = [
${modelEntries.join(",\n")}
];

export function getModelBySlug(slug: string): ModelDetail | undefined {
  return modelDetails.find((m) => m.slug === slug);
}
`;

  saveDataFile("models.ts", modelsTs);

  // Generate src/data/model-slugs.ts for generateStaticParams
  const slugs = models.map((m) => m.slug);
  const slugsTs = `// Auto-generated by pipeline/generate-data-files.ts
// Last updated: ${new Date().toISOString()}

export const allModelSlugs: string[] = ${JSON.stringify(slugs, null, 2)};
`;
  saveDataFile("model-slugs.ts", slugsTs);

  console.log(`  Generated ${models.length} models in models.ts and model-slugs.ts`);

  return {
    modelsGenerated: models.length,
    filesWritten: ["src/data/models.ts", "src/data/model-slugs.ts"],
  };
}