// Auto-generated by pipeline/generate-data-files.ts
// Last updated: 2026-07-02T10:54:15.111Z
// Source: Models table (is_japanese, developer, category)
// DO NOT EDIT MANUALLY

export type JpCapabilityLevel = "native" | "high" | "moderate" | "low" | "untested";

export interface JpCapability {
  slug: string;
  name: string;
  developer: string;
  jpLevel: JpCapabilityLevel;
  badgeJa: string;
  badgeEn: string;
  japaneseMtBench: number | null;
  jglue: number | null;
  jmmlu: number | null;
  descriptionJa: string;
  descriptionEn: string;
}

export const jpCapabilityData: JpCapability[] = [
  {
    "slug": "elyza-thinking-1-0-qwen-32b",
    "name": "ELYZA-Thinking-1.0-Qwen-32B",
    "developer": "ELYZA",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "llama-3-elyza-jp-8b",
    "name": "Llama-3-ELYZA-JP-8B",
    "developer": "ELYZA",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "llama-3-namazu-405b",
    "name": "Llama-3-Namazu-405B",
    "developer": "Sakana AI",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "namazu-deepseek-v3-1",
    "name": "Namazu-DeepSeek-V3.1-Terminus",
    "developer": "Sakana AI",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "plamo-2-0",
    "name": "PLaMo 2.0",
    "developer": "Preferred Networks",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "youri-7b",
    "name": "Youri-7B",
    "developer": "rinna",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "takane",
    "name": "たかね (Takane)",
    "developer": "富士通",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "tsuzumi",
    "name": "つづみ (tsuzumi)",
    "developer": "NTT",
    "jpLevel": "native",
    "badgeJa": "ネイティブJP",
    "badgeEn": "Native JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "日本企業が開発したモデルまたは日本語に特化したモデル。日本語の理解・生成能力が最も高い。",
    "descriptionEn": "Model developed by a Japanese company or specialized for Japanese. Highest Japanese understanding and generation capability."
  },
  {
    "slug": "claude-mythos-preview",
    "name": "Claude Mythos Preview",
    "developer": "Anthropic",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "claude-opus-4-7",
    "name": "Claude Opus 4.7",
    "developer": "Anthropic",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "claude-opus-4-8",
    "name": "Claude Opus 4.8",
    "developer": "Anthropic",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "deepseek-v3-2",
    "name": "DeepSeek V3.2",
    "developer": "DeepSeek",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "gpt-5-1-codex-max",
    "name": "GPT-5.1 Codex Max",
    "developer": "OpenAI",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "gpt-5-2",
    "name": "GPT-5.2",
    "developer": "OpenAI",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "gemini-3-0-pro",
    "name": "Gemini 3.0 Pro",
    "developer": "Google DeepMind",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "gemma-4-31b",
    "name": "Gemma 4 31B",
    "developer": "Google DeepMind",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "grok-4-2-beta",
    "name": "Grok 4.2 Beta",
    "developer": "xAI",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  },
  {
    "slug": "qwen3-6-27b",
    "name": "Qwen3.6-27B",
    "developer": "Alibaba",
    "jpLevel": "high",
    "badgeJa": "高品質日本語",
    "badgeEn": "High-Quality JP",
    "japaneseMtBench": null,
    "jglue": null,
    "jmmlu": null,
    "descriptionJa": "多言語対応モデルのうち、日本語処理に優れた性能を持つモデル。",
    "descriptionEn": "Multilingual model with strong Japanese language processing capabilities."
  }
];

export function getJpCapabilityBySlug(slug: string): JpCapability | undefined {
  return jpCapabilityData.find((c) => c.slug === slug);
}
