// Auto-generated by generate-leaderboard-data.ts
// Last updated: 2026-05-14T02:56:33.669Z
// Source: datalearner.com leaderboard data
// DO NOT EDIT MANUALLY

export interface ModelRanking {
  rank: number;
  name: string;
  developer: string;
  hle: number | null;
  arcAgi2: number | null;
  frontierMath: number | null;
  sweBenchVerified: number | null;
  tauBench: number | null;
  openSource: "open" | "closed" | "open-nc";
  type: "reasoning" | "foundation" | "chat" | "coder";
  releaseDate: string;
}

export const leaderboardData: ModelRanking[] = [];
