// Auto-generated by pipeline/generate-data-files.ts
// Last updated: 2026-05-17T03:38:31.251Z
// Source: SQLite database (pricing_entries table)
// DO NOT EDIT MANUALLY

export type BillingMode = "standard" | "batch" | "cache" | "long-context";

export interface PricingEntry {
  modelName: string;
  provider: string;
  billingMode: BillingMode;
  inputPrice: number;
  outputPrice: number;
  inputModality: "text" | "multimodal";
  outputModality: "text" | "multimodal";
  releaseDate: string;
  notes?: string;
}

export const pricingData: PricingEntry[] = [
  {
    "modelName": "Qwen3.6-27B",
    "provider": "Alibaba",
    "billingMode": "standard",
    "inputPrice": 0.35,
    "outputPrice": 1.4,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-22"
  },
  {
    "modelName": "Anthropic Claude Opus 4.6",
    "provider": "Anthropic",
    "billingMode": "standard",
    "inputPrice": 2.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-05"
  },
  {
    "modelName": "Claude Mythos Preview",
    "provider": "Anthropic",
    "billingMode": "standard",
    "inputPrice": 15,
    "outputPrice": 75,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-08"
  },
  {
    "modelName": "Claude Opus 4.1",
    "provider": "Anthropic",
    "billingMode": "standard",
    "inputPrice": 7.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-08-06"
  },
  {
    "modelName": "Claude Opus 4.5",
    "provider": "Anthropic",
    "billingMode": "standard",
    "inputPrice": 2.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-11-25"
  },
  {
    "modelName": "Claude Opus 4.7",
    "provider": "Anthropic",
    "billingMode": "standard",
    "inputPrice": 15,
    "outputPrice": 75,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-16"
  },
  {
    "modelName": "Claude Sonnet 4.6",
    "provider": "Anthropic",
    "billingMode": "standard",
    "inputPrice": 3,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-17"
  },
  {
    "modelName": "Composer 1",
    "provider": "Cursor",
    "billingMode": "standard",
    "inputPrice": 1.25,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-10-29"
  },
  {
    "modelName": "Cursor Composer 1.5",
    "provider": "Cursor",
    "billingMode": "standard",
    "inputPrice": 3.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-09"
  },
  {
    "modelName": "Cursor Composer 2",
    "provider": "Cursor",
    "billingMode": "standard",
    "inputPrice": 0.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-19"
  },
  {
    "modelName": "DeepSeek V3.2",
    "provider": "DeepSeek",
    "billingMode": "standard",
    "inputPrice": 0.27,
    "outputPrice": 1.1,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-28"
  },
  {
    "modelName": "DeepSeek V4 Flash",
    "provider": "DeepSeek",
    "billingMode": "standard",
    "inputPrice": 0.14,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24"
  },
  {
    "modelName": "DeepSeek V4 Pro",
    "provider": "DeepSeek",
    "billingMode": "standard",
    "inputPrice": 1.74,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24"
  },
  {
    "modelName": "deepseek-v4-flash",
    "provider": "DeepSeek",
    "billingMode": "cache",
    "inputPrice": 0.0028,
    "outputPrice": 0.28,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュヒット時の入力価格"
  },
  {
    "modelName": "deepseek-v4-flash",
    "provider": "DeepSeek",
    "billingMode": "standard",
    "inputPrice": 0.14,
    "outputPrice": 0.28,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュミス時の入力価格"
  },
  {
    "modelName": "deepseek-v4-pro",
    "provider": "DeepSeek",
    "billingMode": "cache",
    "inputPrice": 0.003625,
    "outputPrice": 0.87,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュヒット時の入力価格。2026/05/31まで75%割引適用中"
  },
  {
    "modelName": "deepseek-v4-pro",
    "provider": "DeepSeek",
    "billingMode": "standard",
    "inputPrice": 0.435,
    "outputPrice": 0.87,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-24",
    "notes": "キャッシュミス時の入力価格。2026/05/31まで75%割引適用中"
  },
  {
    "modelName": "ELYZA-Thinking-1.0-Qwen-32B",
    "provider": "ELYZA",
    "billingMode": "standard",
    "inputPrice": 80,
    "outputPrice": 320,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-01-15"
  },
  {
    "modelName": "Llama-3-ELYZA-JP-8B",
    "provider": "ELYZA",
    "billingMode": "standard",
    "inputPrice": 30,
    "outputPrice": 120,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-07-01"
  },
  {
    "modelName": "Gemini 3.1 Pro Preview",
    "provider": "Google Deep Mind",
    "billingMode": "standard",
    "inputPrice": 2,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-20"
  },
  {
    "modelName": "Gemini 3.0 Pro",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 1.25,
    "outputPrice": 5,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-15"
  },
  {
    "modelName": "Gemini 3.1 Flash Live Preview",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.75,
    "outputPrice": 4.5,
    "inputModality": "multimodal",
    "outputModality": "multimodal",
    "releaseDate": "2026-05-17",
    "notes": "テキスト価格。音声と画像/動画は別途分単位の課金あり"
  },
  {
    "modelName": "Gemini 3.1 Flash ライブ プレビュー",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.75,
    "outputPrice": 4.5,
    "inputModality": "multimodal",
    "outputModality": "multimodal",
    "releaseDate": "2026-05-17",
    "notes": "テキスト価格。音声・画像/動画は時間単位または別料金"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 0.125,
    "outputPrice": 0.75,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "テキスト/画像/動画は$0.125、音声は$0.25"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.45,
    "outputPrice": 2.7,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "優先度階層。テキスト/画像/動画は$0.45、音声は$0.90"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite Preview",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 0.125,
    "outputPrice": 0.75,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "プレビュー版。音声入力は$0.25/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite Preview",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.25,
    "outputPrice": 1.5,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "テキスト/画像/動画は$0.25、音声は$0.50"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite プレビュー",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 0.125,
    "outputPrice": 0.75,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "音声入力の場合は0.25ドル/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Flash-Lite プレビュー",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.25,
    "outputPrice": 1.5,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "音声入力は0.50ドル/1Mトークン"
  },
  {
    "modelName": "Gemini 3.1 Pro Preview",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 1,
    "outputPrice": 6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-02-20",
    "notes": "プロンプト <= 200,000 トークンの場合。それ以上の場合は入力$2.00/出力$9.00"
  },
  {
    "modelName": "Gemini 3.1 Pro Preview",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 3.6,
    "outputPrice": 21.6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-02-20",
    "notes": "優先度階層。プロンプト <= 20万トークンの場合。それ以上の場合は入力$7.20/出力$32.40"
  },
  {
    "modelName": "Gemini 3.1 Pro プレビュー版",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 1,
    "outputPrice": 6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "プロンプト20万トークン以下。20万トークン超の場合は入力2.0ドル、出力9.0ドル"
  },
  {
    "modelName": "Gemini 3.1 Pro プレビュー版",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 3.6,
    "outputPrice": 21.6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "優先度プラン。プロンプト20万トークン以下。20万トークン超の場合は入力7.2ドル、出力32.4ドル"
  },
  {
    "modelName": "gemini-3.1-flash-lite",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 0.125,
    "outputPrice": 0.75,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "テキスト/画像/動画は0.125、音声は0.25"
  },
  {
    "modelName": "gemini-3.1-flash-lite",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.45,
    "outputPrice": 2.7,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "優先度プラン。テキスト/画像/動画は0.45、音声は0.90"
  },
  {
    "modelName": "gemini-3.1-flash-lite-preview",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.25,
    "outputPrice": 1.5,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-05-17",
    "notes": "プレビュー版。テキスト/画像/動画は0.25、音声は0.50"
  },
  {
    "modelName": "gemini-3.1-flash-live-preview",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 0.75,
    "outputPrice": 4.5,
    "inputModality": "multimodal",
    "outputModality": "multimodal",
    "releaseDate": "2026-05-17",
    "notes": "テキスト価格。音声と画像/動画は別途分単位料金あり"
  },
  {
    "modelName": "gemini-3.1-pro-preview",
    "provider": "Google DeepMind",
    "billingMode": "batch",
    "inputPrice": 1,
    "outputPrice": 6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-02-20",
    "notes": "プロンプト <= 200,000 トークンの場合。200,000 トークン超は入力2.00/出力9.00"
  },
  {
    "modelName": "gemini-3.1-pro-preview",
    "provider": "Google DeepMind",
    "billingMode": "standard",
    "inputPrice": 3.6,
    "outputPrice": 21.6,
    "inputModality": "multimodal",
    "outputModality": "text",
    "releaseDate": "2026-02-20",
    "notes": "優先度プラン。プロンプト <= 20万トークンの場合。20万超は入力7.20/出力32.40"
  },
  {
    "modelName": "MiniMax M2.5",
    "provider": "MiniMaxAI",
    "billingMode": "standard",
    "inputPrice": 0.3,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-12"
  },
  {
    "modelName": "MiniMax-M2.7",
    "provider": "MiniMaxAI",
    "billingMode": "standard",
    "inputPrice": 0.3,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-18"
  },
  {
    "modelName": "Kimi K2.6",
    "provider": "Moonshot AI",
    "billingMode": "standard",
    "inputPrice": 0.95,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-20"
  },
  {
    "modelName": "GPT-5.1 Codex Max",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 2.5,
    "outputPrice": 15,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-10"
  },
  {
    "modelName": "GPT-5.1 Instant",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 1.25,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-11-12"
  },
  {
    "modelName": "GPT-5.2",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 1.25,
    "outputPrice": 10,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-20"
  },
  {
    "modelName": "GPT-5.4",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 2.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-05"
  },
  {
    "modelName": "GPT-5.4 Pro",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 30,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-05"
  },
  {
    "modelName": "GPT-5.4 mini",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 0.375,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-17"
  },
  {
    "modelName": "GPT-5.4 nano",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 0.1,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-17"
  },
  {
    "modelName": "GPT-5.5",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 2.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-23"
  },
  {
    "modelName": "GPT-5.5 Pro",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 30,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-23"
  },
  {
    "modelName": "GPT-image-2",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 8,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-21"
  },
  {
    "modelName": "OpenAI GPT-5.2",
    "provider": "OpenAI",
    "billingMode": "standard",
    "inputPrice": 0.875,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-12-11"
  },
  {
    "modelName": "PLaMo 2.0",
    "provider": "Preferred Networks",
    "billingMode": "standard",
    "inputPrice": 50,
    "outputPrice": 200,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-01"
  },
  {
    "modelName": "Test Model",
    "provider": "Test Provider",
    "billingMode": "standard",
    "inputPrice": 1,
    "outputPrice": 2,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-08"
  },
  {
    "modelName": "Grok 4.2 Beta",
    "provider": "xAI",
    "billingMode": "standard",
    "inputPrice": 5,
    "outputPrice": 15,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-08"
  },
  {
    "modelName": "GLM 5.1",
    "provider": "Zhipu AI",
    "billingMode": "standard",
    "inputPrice": 1.4,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-27"
  },
  {
    "modelName": "GLM-5",
    "provider": "Zhipu AI",
    "billingMode": "standard",
    "inputPrice": 1,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-11"
  },
  {
    "modelName": "GLM-5-Turbo",
    "provider": "Zhipu AI",
    "billingMode": "standard",
    "inputPrice": 1.2,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-15"
  },
  {
    "modelName": "Qwen 3.6 Plus Preview",
    "provider": "アリババ",
    "billingMode": "standard",
    "inputPrice": 0.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-03-31"
  },
  {
    "modelName": "Qwen3-30B-A3B-Instruct-2507",
    "provider": "アリババ",
    "billingMode": "standard",
    "inputPrice": 0.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2025-07-29"
  },
  {
    "modelName": "Qwen3.5-397B-A17B",
    "provider": "アリババ",
    "billingMode": "standard",
    "inputPrice": 0.5,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-02-16"
  },
  {
    "modelName": "Qwen3.6-Max-Preview",
    "provider": "アリババ",
    "billingMode": "standard",
    "inputPrice": 1.3,
    "outputPrice": 0,
    "inputModality": "text",
    "outputModality": "text",
    "releaseDate": "2026-04-20"
  }
];
